### ISSUE TITLE
Error 1493987134017316 - 300 - No se encontro el Sistema de Gestión (SGP) 

### ISSUE THREAD

**Issue by danicomas** [miamon/Face-Web-Service#1]
¿A que se refiere el siguiente código de error?:

**1493987134017316 - 300 - No se encontro el Sistema de Gestión (SGP)  Emisor "FNMT" Serie "X"**

STAGE: (https://se-face-webservice.redsara.es/sspp?wsdl)
@miamon He visto que comentas que los WS de **STAGE no funcionan correctamente**. ¿Puede que este error sea por esto?

PD: La factura de prueba la he hecho con la aplicación facturae firmando con el mismo certificado usado para enviar y el PEM es el mismo que el pfx pasado a .cer

**Comment by miamon** [comment]
No te sabría decir que error daba, Si lees comentarios es http://sviudes.blogspot.com.es/2010/05/facturae-con-net-y-c.html algunos usuarios reportaban errores de WS de Stage y por eso apunté deirectamente a produccion. Pero con ello también salta error, a mi en concreto  310 - Algún parametro obligatorio aparece vacío

**Comment by miamon** [comment]
Si apunto el servicio a https://se-face-webservice.redsara.es/sspp2?wsdl me da el error que comentas. Saludos

**Comment by danicomas** [comment]
Muchas Gracias @miamon

**Comment by phx255** [comment]
El problema es que no estás dado de alta como proveedor en el Stage. Tienes que enviar un mail a soporte especificando el PEM de tu certificado.
De todos modos, yo lo he echo y no he tenido respuesta. Solo podemos "probar" en producción.
Un saludo.
